//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSummary", ReplyAction="http://tempuri.org/IService1/GetSummaryResponse")]
        System.Data.DataSet GetSummary();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSummary", ReplyAction="http://tempuri.org/IService1/GetSummaryResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetSummaryAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllDepartments", ReplyAction="http://tempuri.org/IService1/GetAllDepartmentsResponse")]
        System.Data.DataSet GetAllDepartments();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllDepartments", ReplyAction="http://tempuri.org/IService1/GetAllDepartmentsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetAllDepartmentsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WpfApp1.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WpfApp1.ServiceReference1.IService1>, WpfApp1.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetSummary() {
            return base.Channel.GetSummary();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetSummaryAsync() {
            return base.Channel.GetSummaryAsync();
        }
        
        public System.Data.DataSet GetAllDepartments() {
            return base.Channel.GetAllDepartments();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetAllDepartmentsAsync() {
            return base.Channel.GetAllDepartmentsAsync();
        }
    }
}
